### ISSUE TITLE
explicit disable for router module - prevents startup when migrating from cuckoo-modified

### ISSUE THREAD

**Issue by mallorybobalice** [doomedraven/cuckoo-modified#10]
@doomedraven 

hey,

loved the idea of rooter per analysis at the time ,still do, but don't use it. 
I've merged in the router related bits into cuckoo config, 
but are you guys sure there's isn't a bug in startup.py?
even with explicit disable for router module  (presumably above) - prevents startup when migrating from cuckoo-modified

seems to exit on exceptions inside the interface checks even though I said router=none and internet=none, tor=off, inetsim=off

I've ended up just emptying  the bit in startup.py

````
def init_routing():
    """Initialize and check whether the routing information is correct."""
    cuckoo = Config()
````

it still says critical error connecting to rooter (form init_rooter) (yes i know it's not set up at all , and won't be for now =) , shouldn't none suppress those but at least analysis continues?)
conf :
````
# this part must be inside of [cuckoo]
# Path to the unix socket for running root commands.
rooter = /tmp/cuckoo-rooter

[routing]
route = none

internet = none

rt_table = main

auto_rt = yes

inetsim = off
inetsim_server = inetsim_ip
inetsim_interface = virbr0

tor = off
tor_dnsport = 5353
tor_proxyport = 9040
tor_interface = virbr0


````

**Comment by doomedraven** [comment]
rooter should be started anyway now and first, before start the rest, you can't disable it, it managing all routes, so that is not a bug, my friend yesterday deployed it and it works fine :P

**Comment by mallorybobalice** [comment]
=) mmm, what's the benefit of enabling it if I don't use it?(extra bit that can break)
many people migrating from just CB-M would experience startup issues - personally I think it's better to let people 'not use it'

**Comment by doomedraven** [comment]
`there no way to not use it`, i using it since cuckoo v2 had it, and backported, there even was issue in Brads repo if is ok to create pull req. i found more people who got benefits from that than cons, so sorry, people who don't want it, can fork brads repo and follow it, but this enables much more easier extension of routes to use, and it makes more safes routes than before, to prevent leakead traffic

`experience startup issues` that is not an issue, you just need to start rooter and done :)

**Comment by mallorybobalice** [comment]
OK err can you please confirm the config above won't try to add any new routes (yes I read the issue comments for the csbm pull req, from memory they're magical per machine ip. But basically I don't want it to touch routes or iptables at all when running, at all. )

**Comment by mallorybobalice** [comment]
Ps is there a rtfm for setting up rooter and a systemd wrapper?

**Comment by doomedraven** [comment]
systemd for what? for start? i have supervisor for it

for rooter -> `-h` :D

```
[program:cuckoo]
command=python cuckoo.py
directory=/opt/cuckoo-modified/
user=cuckoo
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/cuckoo.err.log
stdout_logfile=/var/log/supervisor/cuckoo.out.log

[program:cuckoo_web]
command=python manage.py runserver 0.0.0.0:8000
directory=/opt/cuckoo-modified/web
user=cuckoo
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/web.err.log
stdout_logfile=/var/log/supervisor/web.out.log
stopasgroup=true

[program:cuckoo_process]
command=python process.py -p20 auto
user=cuckoo
directory=/opt/cuckoo-modified//utils
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/process.err.log
stdout_logfile=/var/log/supervisor/process.out.log

[program:rooter]
command=python rooter.py
directory=/opt/cuckoo-modified/utils
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/routetor.err.log
stdout_logfile=/var/log/supervisor/routetor.out.log
```

**Comment by mallorybobalice** [comment]
kinda. =) guess i'm not familiar with supervisor and you're not familiar with systemd ?

````
vi /lib/systemd/system/cuckoorooter.service
[Unit]
Description=Cuckoo rooter dependency
After=network.target

[Service]
User=root
Group=root
ExecStart=/usr/bin/python2.7 /.../utils/rooter.py
WorkingDirectory=<snip>
Restart=always
RestartSec=10s


[Install]
WantedBy=multi-user.target
````


vi /lib/systemd/system/cuckoomain.service
````
[Unit]
Description=Main Cuckoo service wrapper
After=network.target mysql.service mongod.service libvirtd.service cuckoorooter.service

[Service]
User=cuckoo
Group=cuckoo
ExecStart=/usr/bin/python2.7 cuckoo.py --debug
WorkingDirectory=<snip>
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
````

**Comment by mallorybobalice** [comment]
so to double check

this in cuckoo.conf provided I have rooter started means 
don't touch routes?

````
# this part must be inside of [cuckoo]
# Path to the unix socket for running root commands.
rooter = /tmp/cuckoo-rooter

[routing]
route = none

internet = none

rt_table = main

auto_rt = yes

inetsim = off
inetsim_server = inetsim_ip
inetsim_interface = virbr0

tor = off
tor_dnsport = 5353
tor_proxyport = 9040
tor_interface = virbr0
````
yes/no/maybe?

**Comment by doomedraven** [comment]
it's depend, what you want as default exit for all traffic
