### ISSUE TITLE
web ui and tagging behaviour?

### ISSUE THREAD

**Issue by mallorybobalice** [doomedraven/cuckoo-modified#12]
=( mmmm....if all my machines are 'have all the apps installed' - what do i do to direct samples to any? 
tried the web ui after upgrade - getting this (vs submit.py) 
````
2017-07-27 19:50:52,703 [lib.cuckoo.core.scheduler] ERROR: Task #1482: Cannot acquire machine: No machines match selection criteria.
2017-07-27 19:50:52,722 [lib.cuckoo.core.scheduler] DEBUG: Task #1482: Released database task with status False
````

**Comment by doomedraven** [comment]
no idea what are you speaking about, and more details whould be good

**Comment by mallorybobalice** [comment]
hmm... ok, 

say in my machinery.conf

````
machines = T_CSB_CLI_Win7_X64_001,T_CSB_CLI_Win7_X64_002

[T_CSB_CLI_morelabelstuff1]
label = T_CSB_CLI_morelabelstuff1
platform = windows
snapshot = CSBRevertTo
ip = <snip>
tags = Win7x,ReaderX,OfficeX,JavaX,FlashX,IEX
````
all the vms are like that. 

after merging in the latest source (vs say last september) 
I now get 'Cannot acquire machine: No machines match selection criteria.' in cuckoo.log 
Is there some sort of tag to package system or some extra bits i need in machinery to indicate 'just pipe it to a random machine, I don't mind'?

**Comment by mallorybobalice** [comment]
ps doesn't seem to matter for submit.py :\

**Comment by mallorybobalice** [comment]
hmmm @doomedraven  - sorry. 
not sure what i pressed (didn't fill in any select boxes. but can't seem to reproduce it . 👍 )

hopefully that's it from me for a few weeks :) thanks for the help again.
