### ISSUE TITLE
Scheduler.py global name "machine"

### ISSUE THREAD

**Issue by big-gunter** [doomedraven/cuckoo-modified#16]
There appears to be an issue in scheduler.py, around line 668. This relates to the implementation of the VPN forwarding. 

When executing cuckoo.py, the following error is received:

```
2017-08-15 14:21:34,674 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager with max_analysis_count=1, max_machines_count=2, and max_vmstartup_count=1
2017-08-15 14:21:37,936 [lib.cuckoo.core.scheduler] INFO: Loaded 6 machine/s
Traceback (most recent call last):
  File "cuckoo.py", line 133, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "cuckoo.py", line 79, in cuckoo_main
    sched.start()
  File "/home/exodus/doomedraven/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 678, in start
    self.initialize()
  File "/home/exodus/doomedraven/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 668, in initialize
    rooter("forward_disable", machines.interface,self.cfg.routing.internet, machines.ip)
NameError: global name 'machines' is not defined
```
I've had a bit of play but am yet to work it out...

**Comment by big-gunter** [comment]
I've done a bit of code review/comparison. The issue with the variable occurs for the obvious reason of `machine` not being defined. I had a hunt through the official Cuckoo repo, this appears to be because in the 2.0 version of the scheduler.py, `machine` is defined in an over arching `for` loop.

` for machine in machinery.machines():
            if not machine.interface:
                log.info("Unable to determine the network interface for VM "
                         "with name %s, Cuckoo will not be able to give it "
                         "full internet access or route it through a VPN! "
                         "Please define a default network interface for the "
                         "machinery or define a network interface for each "
                         "VM.", machine.name)
                continue

            # Drop forwarding rule to each VPN.
            if config("routing:vpn:enabled"):
                for vpn in config("routing:vpn:vpns"):
                    rooter(
                        "forward_disable", machine.interface,
                        config("routing:%s:interface" % vpn), machine.ip
                    )

            # Drop forwarding rule to the internet / dirty line.
            if config("routing:routing:internet") != "none":
                rooter(
                    "forward_disable", machine.interface,
                    config("routing:routing:internet"), machine.ip
)`

I'll keep hunting for a solution, as I don't simply want to much the code together. Anyone else that comes across this, simply commenting out the VPN lines in scheduler.py allows it to work without VPN functionality:

`        # Drop forwarding rule to each VPN.
#        for vpn in vpns.values():
#           rooter("forward_disable", machines.interface,vpn.interface, machine.ip)

        # Drop forwarding rule to the internet / dirty line.
#        if self.cfg.routing.internet != "none":
#           rooter("forward_disable", machine.interface,self.cfg.routing.internet, machine.ip)
`

**Comment by big-gunter** [comment]
Ok, not sure if this is the correct solution, however declaring the variable in a `for` loop prior to the VPN entries seems to solve the issue.

Replace the following (starting line 662):
 ```
       # Drop forwarding rule to each VPN.
        for vpn in vpns.values():
            rooter("forward_disable", machine.interface,vpn.interface, machine.ip)

        # Drop forwarding rule to the internet / dirty line.
        if self.cfg.routing.internet != "none":
rooter("forward_disable", machine.interface,self.cfg.routing.internet, machine.ip)
```

With:
```
        for machine in machinery.machines():
        # Drop forwarding rule to each VPN.
                for vpn in vpns.values():
                        rooter("forward_disable", machines.interface,vpn.interface, machine.ip)

        # Drop forwarding rule to the internet / dirty line.
                if self.cfg.routing.internet != "none":
                        rooter("forward_disable", machine.interface,self.cfg.routing.internet, machine.ip)
```

The existing for and if loops aren't modified, but are provided for reference.

I'll wait to see if the dev agrees with this solution before closing the issue.

**Comment by big-gunter** [comment]
While the above allows the cuckoo.py process to run, it prevents execution and causes errors. Subsequently, the above is not a solution!

**Comment by doomedraven** [comment]
that is defined

https://github.com/doomedraven/cuckoo-modified/blob/master/lib/cuckoo/core/scheduler.py#L622

which hypervisor do you use? it works fine for me on kvm

**Comment by big-gunter** [comment]
Virtualbox is running the sandboxes. Line 662 uses the variable machine - not machinery (as defined in line 622).. perhaps that's the issue.

**Comment by doomedraven** [comment]
oh i see, that is weird how it then works just fine for me, thanks i will investigate it, i hope this evening

**Comment by doomedraven** [comment]
i think there missed 

```
for machine in machinery.machines():
```

will test later

**Comment by doomedraven** [comment]
yup

https://github.com/cuckoosandbox/cuckoo/blob/7b9cea896cb77e09ba4d1bf72aa4e5abd4a688c1/cuckoo/core/scheduler.py#L826

weird but how it works here with kvm but well will add it in a bit

**Comment by big-gunter** [comment]
It appears to be working, I'm getting an error, but it's a config file error as I haven't defined a default network interface in the virtualbox.conf.

I'll set that up in the morning tomorrow and report back.

**Comment by big-gunter** [comment]
Have amended the virtualbox.conf which alleviated the interface issue, however cuckoo.py errors out:

```
2017-08-18 07:06:56,309 [lib.cuckoo.core.scheduler] INFO: Loaded 6 machine/s
Traceback (most recent call last):
  File "cuckoo.py", line 133, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "cuckoo.py", line 79, in cuckoo_main
    sched.start()
  File "/home/exodus/doomedraven/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 693, in start
    self.initialize()
  File "/home/exodus/doomedraven/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 677, in initialize
    if self.vpn_cfg.vpn.enabled:
AttributeError: Scheduler instance has no attribute 'vpn_cfg'
```

**Comment by doomedraven** [comment]
https://github.com/doomedraven/cuckoo-modified/commit/d52a43191b6030934b4e093a4a22c56ee53c9924#diff-a88cf3791b068d754bd7dab6e311e018R74

did you update whole file?

**Comment by big-gunter** [comment]
Yep, have just double checked and pulled a fresh clone from github also. Same result.

**Comment by doomedraven** [comment]
ok check now, i did fail and pushed it to another class :D

**Comment by big-gunter** [comment]
Seems to be working!! I'll push a couple of samples through, if all goes to plan I'll close the issue.

**Comment by doomedraven** [comment]
Thanks for reporting :)
