### ISSUE TITLE
ransom Yara Rule 

### ISSUE THREAD

**Issue by Nwinternights** [doomedraven/cuckoo-modified#3]
I write here cause @doomedraven should open "issue" tabs on Comunity-modified :-)
@kevross did an interesting yara rule for detecting ransom message
https://github.com/cuckoosandbox/cuckoo/pull/1625/files

**Comment by doomedraven** [comment]
Oh thanks i will add it in few hours

**Comment by doomedraven** [comment]
https://github.com/doomedraven/community-modified/issues :)
