### ISSUE TITLE
rooter.py contains an error

### ISSUE THREAD

**Issue by big-gunter** [doomedraven/cuckoo-modified#4]
Rooter.py fails to launch of this commit due to line 134.

At line 134 there is a "3" at the begining, removing the "3" and adjusting the space accordingly allows Rooter.py to run correctly.

Cheers

**Comment by doomedraven** [comment]
thanks, fixed, can i close this? ;)

**Comment by big-gunter** [comment]
Yeah, I've got some other issues - but pretty sure it's my setup and they're not related ot this.

**Comment by doomedraven** [comment]
feel free to ask for help

**Comment by big-gunter** [comment]
Thanks! One thing I just picked up (I haven't done a pull since the old modifed fork closed), there's no [tor] entry in auxilary.conf, which in turn prevents mine from starting, even with tor = off in cuckoo.conf. 

Simply adding the [tor] entry, from the old fork, back in seemed to fix it.

The one that has me stumped is in submissions/views.py, django/python throws an error relating to the vpn - line 401. Commenting it out allows the submission page to load, but with it in there it throws an error on the webpage - other than disabling it I can;t work it out :)

**Comment by doomedraven** [comment]
yup, bcz here im using rooter as it more advanced, so config now is in cuckoo.conf
basically without update to this branch with all commints it won't work and you will have some issues, as you have rooter missed integration, at least looks like, but adding tor to aux, it won't route correctly

**Comment by big-gunter** [comment]
Interesting, I figured it may be to do with that. I created a test environment and cloned the current fork (as opposed to a pull/merge), went through and configured it using the configs in the branch - tor still throws an issue when running web/manage.py runserver ip:port. It appears that utils/manage.py is still looking for tor in the auxiliary conf.

**Comment by doomedraven** [comment]
Interesting, can you post issue? I dont have time to check that till monday

**Comment by big-gunter** [comment]
Yeah, I will, just playing with it now - will post it when I've had a bit more of a fiddle :)

**Comment by doomedraven** [comment]
that is interesting i don't know how i had missed imports in push, when i have it working just fine in production
