### ISSUE TITLE
samples of analysis files for example making process.py consume all ram for small input. 

### ISSUE THREAD

**Issue by mallorybobalice** [doomedraven/cuckoo-modified#7]
hi, 

is there any option to send a couple of samples in pw protected 7z directly to say @doomedraven  .
They're of company identifying nature unfortunately. [and I don't want these to be resent to people who haven't patched if this is fixed].
I'm fairly sure as usual this is going to be the static analysis libs.  [in this case pe]

the latest batch I have cause process.py to [very rapidly] allocate all the VMEM and the cuckoo server to crash.
(at the moment there's no watchdog limit process, and as far as I know no plans to limit worker or cumulative worker consumption to avoid similar situations )

thanks,
mb

**Comment by mallorybobalice** [comment]
@doomedraven  leave it wit me for a bit. it looks like our source is a bit old - and since then pefile has been updated, etc. curious if it fixes it.

**Comment by doomedraven** [comment]
ok let me know about progress, about pefile, my suggestion is to use `pefile2` pushed by @jbremer to solve all this pefile pain

**Comment by mallorybobalice** [comment]
> pefile, my suggestion is to use pefile2 pushed by @jbremer to solve all this pefile pain

ummm, bit more detail please? if i merge in the latest source from this repo and install requirements.txt would i be ok or not really?

**Comment by mallorybobalice** [comment]
yup seems like should be ok? 


pefile2==1.2.11
--
28 | git+https://github.com/crackinglandia/pype32.git

**Comment by doomedraven** [comment]
yup here no changes for deps, is the same as in Brads repo, i only added router, is the main change, nothing else

**Comment by mallorybobalice** [comment]
ok thanks =)
@doomedraven  would you mind following me on twitter - so i can pm you just in case (says i can only message people following) - same nick as here. promise to only pm if everything explodes . completely public is just ...errr.

**Comment by mallorybobalice** [comment]
hmmm

````

[  761.024015] Out of memory: Kill process 3372 (python2.7) score 945 or sacrifice child
[  761.024055] Killed process 3372 (python2.7) total-vm:33575280kB, anon-rss:32138784kB, file-rss:172kB
````
o-oh
debug ideas?

**Comment by doomedraven** [comment]
i saw it in past, but that is due to lack of memory in vm, increase vm memory and should be solved

**Comment by doomedraven** [comment]
debug -> https://github.com/fireeye/rvmi :P

**Comment by mallorybobalice** [comment]
Errrr stability wise we need to be able to cap memory per process py child. (And fail analysis if over say 15g per child or 25 total for 5 children) 
32g total if one process grows to 32g the solution is not to increase memory

**Comment by mallorybobalice** [comment]
Re rvmi that's neat, but I think we need more py debugging

**Comment by mallorybobalice** [comment]
>child or 25 total for 5 children)

Or perhaps prevent spawning new children until free mem is over limit


Thoughts?

**Comment by doomedraven** [comment]
o_O hashes?

**Comment by mallorybobalice** [comment]
i re-ran the 'frozen' set (about 20 samples over 2 years ) and it actually looks ok. (there are a few very cpu bound that i might send later, but the pdfs and pes generally process ok. aside from the report size limit but that's expected.

regarding the OOM kills above-I suppose this means the sample causing high memory is something else. 

does each process.py worked get a new pid /process for each task?
**can we get it to print the pid in the process.py log to correlate with the dmesg oom kills.**
[it'd be good to have a supervisor manager type process with limits for each process and total but i'm surmising it won't happen. at least having it print the per task pid would make it easy to debug . then i can review the log in a few days and re-run the offending samples on the test box/send them to you if need be]

**Comment by doomedraven** [comment]
IS why @jbremer rewrote process.py

**Comment by doomedraven** [comment]
About last question im not sure, im afk so i will check it on monday

**Comment by mallorybobalice** [comment]
Thanks

Mm as in, in csb2.0? 

Well I did plead with Brad before but heh(there are some weird fork and join bugs too) . (Yes yes oss non commercial, I know) 

This and not yet zer0mon and no embedded ole support are at the moment the major bugbears =)

**Comment by doomedraven** [comment]
No idea what is csb, but cuckoo 2 yes

**Comment by jbremer** [comment]
@mallorybobalice we're working on zer0m0n actually, it's going to be integrated in our upcoming release or the next one after ;-) What do you mean regarding embedded OLE support, samples? That sounds like something that is supported already.
@doomedraven "csb" -> Cuckoo Sandbox (IIRC)

**Comment by mallorybobalice** [comment]
@jbremer 
say emebedded lnk or vbs scripts in word docs (requiring user click on say a pic). Some commercial sandboxes trigger each embedded file within the analysis after extracting 
https://blogs.technet.microsoft.com/mmpc/2016/06/14/wheres-the-macro-malware-author-are-now-using-ole-embedding-to-deliver-malicious-files/

I didn't think that was supported. But it sure is widely used. 
Directly or via resubmit+dropped ?

Same with mouse over ppsx /pps 


Thought we already talked about both and the answer was maybe sflock someday? 
https://github.com/spender-sandbox/cuckoo-modified/issues/458

**Comment by jbremer** [comment]
Gotcha, that isn't supported yet indeed :) if you have thoughts on implementation, let me know. AFAIK -modified doesn't do it either, right?

**Comment by mallorybobalice** [comment]
Correct neither do it and I'm sad =(. 
I'm just a girl and all, (as in incomprehensibly hard for me), but why don't we Extract and try to run any unique embedded fils(e.g with sflock?and via dropped or resubmit ) that look executable or scripty . =)? (Like the commercial products (I can name 3 or 
4. In those the embedded files are run in the same vm as the doc (separating tasks via demuxing pre submission or at processing means correlation issues) ) 

As for csb-m. I really wish we had csb2 process.Py in csbm but too hard for me=(

**Comment by doomedraven** [comment]
sflock does the extraction of doc from pdf for example, which formats do you miss? hashes? about submit demuxed well could be but the original idea is better if everything works correctly and pdf drops doc which does it works and saving resources.

well if we got port cuckoo-mod mon to v2, that would be awesome. and basically would be the last dot here, but till then i still need do some small fixes

**Comment by mallorybobalice** [comment]
@doomedraven pdf dropping doc is fine without demuxing. (For many samples human.Py works) 
This is more embedded objects (ole) in office docs (2003 and 2007 plus). 
I think someone mentioned https://github.com/decalage2/oletools to extract too. 
Personally I still think a lot of people would prefer if the extraction and running happened in the submission (else they need to somehow correlate the new file with the original in their SIEM. The latter is somewhat a problem for demuxed zips ) 

https://www.hybrid-analysis.com/sample/f628f332c20a612c2955a5c512d71640ba9d5fd789092aa9bda13a01b5bd7c68?environmentId=100
https://www.hybrid-analysis.com/sample/796a386b43f12b99568f55166e339fcf43a4792d292bdd05dafa97ee32518921?environmentId=100
https://www.hybrid-analysis.com/sample/da82eaeba71eeb95d643b0343b2c095d72b686314cd340631aa8d9fe08a74714?environmentId=100

Issues 
https://github.com/spender-sandbox/cuckoo-modified/issues/458 https://github.com/spender-sandbox/cuckoo-modified/issues/422
Previous discussion

**Comment by doomedraven** [comment]
ah ok yes make sense :)

**Comment by mallorybobalice** [comment]
@doomedraven, 
let's take the composite doc and ole bits into separate issues 
https://github.com/doomedraven/cuckoo-modified/issues/15 
https://github.com/doomedraven/cuckoo-modified/issues/14

in terms of scheduler or process.py could we please get at least get some extra logging added
https://github.com/doomedraven/cuckoo-modified/issues/7#issuecomment-318822874
https://github.com/doomedraven/cuckoo-modified/issues/7#issuecomment-318821466
https://github.com/doomedraven/cuckoo-modified/issues/7#issuecomment-318822805 [to be able to easily id offending tasks causing memory issues] and consider mirroring the csb2 changes (from what I understand at this stage it's a definite no)?

**Comment by mallorybobalice** [comment]
ps for now I've added 
````
    results["statistics"]["reporting"] = list()
    #this
    log.debug("processing data for Task %s, pid is %d", task["id"],os.getpid())
    #yep
    GetFeeds(results=results).run()
````

**Comment by doomedraven** [comment]
feel free to do PR :)

**Comment by mallorybobalice** [comment]
git illiterate =) . I only speak with git humans =)

ok. for basic mem telemetry pre post , this will do

just after 

````
def process(target=None, copy_path=None, task=None, report=False, auto=False):
    # This is the results container. It's what will be used by all the
    # reporting modules to make it consumable by humans and machines.
    # It will contain all the results generated by every processing
    # module available. Its structure can be observed through the JSON
    # dump in the analysis' reports folder. (If jsondump is enabled.)
    results = { }
    results["statistics"] = { }
    results["statistics"]["processing"] = list()
    results["statistics"]["signatures"] = list()
    results["statistics"]["reporting"] = list()
````
add
````
        _proc_status = '/proc/%d/status' % os.getpid()

        try:
            t = open(_proc_status)
            v = t.read()
            t.close()
            i = v.index("Vm")
            w = v[i:].split(None, 3)  # whitespace
            if len(w) >= 3:
                log.debug("mem stats for task %s,pid %d, pre %s",task["id"], os.getpid(),str(w).replace("\\n","|").replace("\\t",'\t'))
        except Exception,e:
            print e
````

and the just before return i suppose.

**Comment by mallorybobalice** [comment]
hello @doomedraven 

ok, it looks like the issue was rat config extraction. 
lib wise i have no idea why. checked apt get and pip requirements + apt update/upgrade and pip list --outdated . made sure re2 was installed (wasn't ) - nothing i can see...


i have no idea why the rat config extracts are just pasted at the end of class PortableExecutable(object):
run function . perhaps it's the best place when everything is in ram but i think it should be default disable optional

so
a) add helper into static.py and process.py :

````
import os
log = logging.getLogger()

def printMemDebug(task,msgtext):
    log.debug("processing data for Task %s, pid is %d", task["id"],os.getpid())
    _proc_status = '/proc/%d/status' % os.getpid()

    # get pseudo file  /proc/<pid>/status
    try:
        t = open(_proc_status)
        v = t.read()
        t.close()
        i = v.index("Vm")
        w = v[i:].split(None, 3)  # whitespace
        if len(w) >= 3:
            print str(w).replace("\\n","|").replace("\\t",'\t')
            log.debug("mem stats for task %s,pid %d, %s, %s",task["id"], os.getpid(),msgtext,str(w).replace("\\n","|").replace("\\t",'\t'))
    except Exception,e:
        print e
````




b) liberally paste into process.py and static.py
add a header into (the bit about task and self task) to pass in the task ref from the outside. 

````
   def __init__(self, task, file_path, results):
        """@param file_path: file path."""
        self.file_path = file_path
        self.pe = None
        self.results = results
        self.task=task
````



`````
    def run(self):
        """Run analysis.
        @return: analysis results dict or None.
        """
        printMemDebug(self.task,"in static pe - start")
        if not os.path.exists(self.file_path):
            return {}

        try:
            self.pe = pefile.PE(self.file_path)
        except pefile.PEFormatError:
            return {}

        results = {}
        peresults = results["pe"] = { }

        pretime = datetime.now()
        printMemDebug(self.task,"in static pe - before peid")
        peresults["peid_signatures"] = self._get_peid_signatures()
        printMemDebug(self.task,"in static pe - after peid")
        posttime = datetime.now()
        timediff = posttime - pretime
        self.add_statistic("peid", "time", float("%d.%03d" % (timediff.seconds, timediff.microseconds / 1000)))

        printMemDebug(self.task,"in static pe - before image base")
        peresults["imagebase"] = self._get_imagebase()
        printMemDebug(self.task,"in static pe - before ep")
        peresults["entrypoint"] = self._get_entrypoint()
        peresults["reported_checksum"] = self._get_reported_checksum()
        peresults["actual_checksum"] = self._get_actual_checksum()
        printMemDebug(self.task,"in static pe - before osver")
        peresults["osversion"] = self._get_osversion()
        peresults["pdbpath"] = self._get_pdb_path()
        printMemDebug(self.task,"in static pe - before sym")
        peresults["imports"] = self._get_imported_symbols()
        printMemDebug(self.task,"in static pe - before exports")
        peresults["exported_dll_name"] = self._get_exported_dll_name()
        peresults["exports"] = self._get_exported_symbols()
        printMemDebug(self.task,"in static pe - before dir")
        peresults["dirents"] = self._get_directory_entries()
        printMemDebug(self.task,"in static pe - before sections")
        peresults["sections"] = self._get_sections()
                                                                         
        printMemDebug(self.task,"in static pe - before sections")
        peresults["sections"] = self._get_sections()
        printMemDebug(self.task,"in static pe - before overlay")
        peresults["overlay"] = self._get_overlay()
        printMemDebug(self.task,"in static pe - before resources")
        peresults["resources"] = self._get_resources()
        printMemDebug(self.task,"in static pe - before iconinfo")
        peresults["icon"], peresults["icon_hash"], peresults["icon_fuzzy"] = self._get_icon_info()
        printMemDebug(self.task,"in static pe - before verinfo")
        peresults["versioninfo"] = self._get_versioninfo()
        peresults["imphash"] = self._get_imphash()
        peresults["timestamp"] = self._get_timestamp()
        printMemDebug(self.task,"in static pe - before digsig")
        peresults["digital_signers"] = self._get_digital_signers()
        peresults["guest_signers"] = self._get_guest_digital_signers()
        printMemDebug(self.task,"in static pe - before imports 2")
        peresults["imported_dll_count"] = len([x for x in peresults["imports"] if x.get("dll")])

        pretime = datetime.now()
        ratname = None
        ratconfig = None
        printMemDebug(self.task,"in static pe - before dc extract")
        #darkcomet_config = darkcomet.extract_config(self.file_path, self.pe)
        #if darkcomet_config:
        #    ratname = "DarkComet"
        #    ratconfig = darkcomet_config
        #njrat_config = njrat.extract_config(self.file_path)
        #if njrat_config:
        #    ratname = "njRAT"
        #    ratconfig = njrat_config
        #nanocore_config = nanocore.extract_config(self.pe)
        #if nanocore_config:
        #    ratname = "NanoCore"
        #    ratconfig = nanocore_config
        posttime = datetime.now()
        timediff = posttime - pretime
        printMemDebug(self.task,"in static pe - after rats")
        self.add_statistic("config_decoder", "time", float("%d.%03d" % (timediff.seconds, timediff.microseconds / 1000)))

        #if ratname:
        #    results["rat"] = { }
        #    results["rat"]["name"] = ratname
        #    results["rat"]["config"] = ratconfig
````

c) figure out that the last step before never exiting and taking all the RAM is 
````
        printMemDebug(self.task,"in static pe - before dc extract")
        darkcomet_config = darkcomet.extract_config(self.file_path, self.pe)
````

**Comment by mallorybobalice** [comment]
note this is not checked back into the code but we've edited it as above for our own code
